project/appointment/urls.py
from django.urls import path
from django.shortcuts import render
from .views import ( calView, meinresView, freeSlots, resView, sloView
                   , adminSlotDelete, adminSlotList
                   )

urlpatterns = [ path ("slot-list", adminSlotList, name="slot-list")
              , path ("slot", sloView, name="slot-create")
              , path ("slot/<int:pk>", sloView, name="slot-update")
              , path ("slot/<int:pk>/delete", adminSlotDelete, name="slot-delete")
              , path ("free-slots", freeSlots, name="free-slots")
              , path ("meine-reservierung", meinresView, name="meires")
              , path ("meine-reservierung/<int:pk>", meinresView, name="meires-detail")
              , path ("reservation", resView, name="reservation-index")
              , path ("reservation/<int:pk>", resView, name="reservation-detail")
              ]

project/user/urls.py
from django.urls import path
from .views import usrView, usrDel

urlpatterns = [ path ("", usrView, name="user-list")
              , path ("<int:pk>/", usrView, name="user-update")
              , path ("<int:pk>/del/", usrDel, name="user-del")
              ]

project/appointment/models.py
from django.db import models
from django.contrib.auth.models import User

class Slot (models.Model):

    class Meta:
        ordering = ["start"]

    start = models.DateTimeField()
    end = models.DateTimeField()

    def __str__(self):
        """To string method."""
        return str(self.start)

class Reservation (models.Model):
    user = models.ForeignKey    ( User
                                , on_delete=models.CASCADE
                                , default=1
                                , related_name="reservation"
                                )
    slot = models.OneToOneField ( Slot
                                , on_delete=models.CASCADE
                                , null=True
                                , related_name="reservation"
                                )
    notes = models.TextField    ( null=True
                                , blank=True
                                )
    confirmed = models.BooleanField ( default = False )
    department = models.CharField (max_length=20, blank=True)

project/appointment/forms.py
from django.contrib.admin import widgets
from django.forms import ModelForm, SplitDateTimeField, TextInput
from django.forms.widgets import SplitDateTimeWidget
from .models import Reservation, Slot

class SlotForm (ModelForm):

    class Meta:
        model = Slot
        fields = ["start", "end"]
        widgets = { 'start': TextInput ( attrs={ 'type': 'datetime-local'
                                               , 'onchange': 'adjust_slot_end(event)'
                                               })
                  , 'end': TextInput (attrs={'type': 'datetime-local'})
                  }

class ReservationForm (ModelForm):

    class Meta:
        model = Reservation
        fields = ["slot", "notes", "department"]

project/appointment/views.py
from django.contrib.auth.models import User
from django.core import mail
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.timezone import localdate
from django.utils.translation import get_language

from babel.dates import format_date, format_datetime
from calendar import monthrange
from datetime import date

from .models import Slot, Reservation
from .forms import ReservationForm, SlotForm
from .calendarHelper import EventCalendar

def meinresView(request, pk=None):

    if not request.user.is_authenticated:
        raise PermissionDenied

    if request.method == "GET" and pk and request.GET.get("delete", None):
        res = Reservation.objects.get(pk=pk)

        lang = get_language()
        subject = "Cancellation of appointment"

        if lang == 'de':
            subject = "Bestätigung Stornierung" 
        else:
            lang = 'en' # make sure language is either 'de' or 'en'

        # email client
        message = render_to_string ( 'cancel_confirmation_{}.jinja'.format(lang)
                                   , { 'first_name': request.user.first_name
                                     , 'last_name': request.user.last_name
                                     }
                                   ) 

        email = mail.EmailMessage ( subject
                                  , message
                                  , 'contact-nmc@unibas.ch'
                                  , [ request.user.email ]
                                  )
        email.send ()

        # email for nmc
        message = '{} {} hat den Slot {} storniert.'.format ( res.user.first_name
                                                            , res.user.last_name
                                                            , res.slot
                                                            )
        email = mail.EmailMessage ( 'Stornierung'
                                  , message
                                  , 'contact-nmc@unibas.ch'
                                  , ['contact-nmc@unibas.ch']
                                  )
        email.send ()
        res.delete()
        return redirect(reverse('meires'))

    elif request.method == "GET":
        today = localdate()
        res = Reservation.objects.filter (user=request.user).filter (slot__start__gte=today)
        v = []
        a = v.append
        for r in res:
            a(render_to_string("meinresLine.html", {"res": r}))
        return render ( request, "meinres.html", {"resTable": v}, )



def resView(request, pk=None):

    if not request.user.is_authenticated:
        raise PermissionDenied

    res = Reservation.objects.get (pk=pk) if pk else Reservation()

    if request.method == "POST":
        form = ReservationForm(request.POST)

        # Staff member wants to confirm a reservation
        if ( not form.is_valid()
             and pk
             and form.data['confirmed'] == 'on'
             and request.user.is_staff
           ):
            res.confirmed = True
            res.save()
            
            lang = get_language()
            subject = "Confirmation of your Studio Days appointment"

            if lang == 'de':
                subject = "Bestätigung Ihres Studio-Days-Termins"
            else:
                lang = 'en' # make sure language is either 'de' or 'en'

            message = render_to_string( 'booking_confirmation_{}.jinja'.format(lang)
                                      , { 'first_name': res.user.first_name
                                        , 'last_name': res.user.last_name
                                        , 'slot': format_datetime(res.slot.start, locale=lang)
                                        }
                                      ) 

            email = mail.EmailMessage( subject
                                     , message
                                     , 'contact-nmc@unibas.ch'
                                     , [ res.user.email ]
                                     )
            email.send()
            return redirect(reverse('slot-list'))

        # new reservation coming in
        elif form.is_valid():
            if not pk:
                res.user = request.user
            res.department = form.cleaned_data["department"]
            res.notes = form.cleaned_data["notes"]
            res.slot = form.cleaned_data["slot"]
            res.save()

            message = render_to_string( 'inform_nmc-team_about_a_new_reservation_de.jinja'
                                      , { 'first_name': request.user.first_name
                                        , 'last_name': request.user.last_name
                                        , 'email': request.user.email
                                        , 'slot': res.slot
                                        }
                                      ) 
            email = mail.EmailMessage( 'Studiodays Reservierung'
                                     , message
                                     , 'contact-nmc@unibas.ch'
                                     , [ 'contact-nmc@unibas.ch' ]
                                     )
            email.send()

            lang = get_language()
            subject = "Confirmation of appointment request"

            if lang == 'de':
                subject = "Bestätigung Terminanfrage" 
            else:
                lang = 'en' # make sure language is either 'de' or 'en'

            message = render_to_string( 'request_confirmation_{}.jinja'.format(lang)
                                      , { 'first_name': request.user.first_name
                                        , 'last_name': request.user.last_name
                                        }
                                      ) 

            email = mail.EmailMessage( subject
                                     , message
                                     , 'contact-nmc@unibas.ch'
                                     , [ request.user.email ]
                                     )
            email.send()

            return redirect(reverse('meires'))

    elif request.method == "GET":
        slotPk = request.GET.get("slot", None)
        slot = None
        form = None
        if slotPk:
            slot = Slot.objects.get(pk=slotPk)
            form = ReservationForm (initial={'slot': slot})
        if pk:
            form = ReservationForm(instance=res)
        else:
            form = ReservationForm(request.GET)
        return render(request, "reservation.html", {"form": form, "slot": slot})

    elif request.method  == "DELETE" and pk:
        res.delete ()

def sloView (request, pk=None):

    if not request.user.is_authenticated:
        raise PermissionDenied

    slot = Slot.objects.get (pk=pk) if pk else Slot ()

    if request.method == "POST":
        form = SlotForm (request.POST)
        if form.is_valid ():
            slot.start = form.cleaned_data["start"]
            slot.end = form.cleaned_data["end"]
            slot.save ()
            return redirect(reverse('slot-list'))

    elif request.method == "GET":
        form = SlotForm (instance=slot) if pk else SlotForm (request.GET)
        return render (request, "slotForm.html", {"form": form})

def calView(request):
    slots = Slot.objects.all()
    yearMonths = sorted (list (set ([ (s.start.year, s.start.month) for s in slots ])))
    cal = EventCalendar()
    monthsHtml = [cal.formatmonth(ym[0],ym[1]) for ym in yearMonths]
    return render ( request
                  , "calendar.html"
                  , { "slots": slots, "cals": monthsHtml }
                  ,
                  )

def adminSlotList(request):
    if not request.user.is_staff:
        raise PermissionDenied
    today = localdate()
    slots = Slot.objects.filter(start__gte=today)
    sList = []
    a = sList.append
    for s in slots:
        a(render_to_string( "adminSlotLine.html"
                          , context = {"date": s, "user": request.user }
                          , request=request
                          ))
    return render ( request, "adminSlots.html", {"htmlSlotList": sList}, )

def adminSlotDelete(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied
    Slot.objects.get(pk=pk).delete()
    return redirect(reverse('slot-list'))

def freeSlots(request):
    today = localdate()
    monthRangeInOneYear = monthrange(today.year+1, today.month)
    overviewEnd  = date(today.year+1, today.month, monthRangeInOneYear[1])
    slots = Slot.objects.filter(start__gte=today).filter(start__lte=overviewEnd).filter(reservation=None)
    sList = []
    a = sList.append
    for s in slots:
        a(render_to_string("bookSlotLine.html", {"date": s, "user": request.user }))
    return render ( request, "freeSlots.html", {"htmlSlotList": sList}, )

project/appointment/templates/adminSlotLine.html
{% load static i18n %}
{% get_current_language as lang %}
<div class="flex-list line {% if date.reservation and not date.reservation.confirmed %} unconfirmed {% endif %}">
  <div class="flex-detail riesig">
    {{ date.start|date:"l" }}, {{ date.start.date }}
  </div>
  <div class="flex-detail lng">
    {{ date.start.time }} - {{ date.end.time }}
  </div>
  <div class="flex-detail mid {% if not date.reservation.department %} empty field {% endif %}">
    {{ date.reservation.department }}
  </div>
  <div class="flex-detail mid {% if not date.reservation.user.email %} empty field {% endif %}"
       style="overflow-wrap: break-word">
    {{ date.reservation.user.email }}
  </div>
  <div class="flex-detail icon-size" style="text-align: center">
    <a href="{% url 'slot-update' date.id %}" class="sd-button">✏️</a>
  </div>
  <div class="flex-detail icon-size">
    {% if date.reservation and not date.reservation.confirmed %} 
    <form class="icon-container"
          action="{% url 'reservation-detail' date.reservation.id %}"
          method="post"
          >
      {% csrf_token %}
      <input
          type="checkbox"
          name="confirmed"
          id="id_confirmed"
          style="display:none"
          checked="true"
          >
      <input
          class="sd-button"
          type="submit"
          value="👍"
          >
    </form>
    {% endif %}
  </div>
  <div class="flex-detail icon-size">
    <form action="{% url 'slot-delete' date.id %}" method="post" style="text-align: center">
      {% csrf_token %}
      <input class="sd-button" type="submit" value="🗑️">
    </form>
  </div>
</div>

project/appointment/templates/adminSlots.html
{% extends "base.html" %}
{% block content %}
{% load static i18n serveContent %}
{% get_current_language as lang %}
<div class="overview"> 
  <a href="{% url 'slot-create' %}">Neuen Slot kreieren</a>
  <div class="flex-list container">
    <div class="flex-list line header">
      <div class="flex-detail riesig">
        {% translate_snippet "Datum" lang %}
      </div>
      <div class="flex-detail lng">
        {% translate_snippet "Zeit" lang %}
      </div>
      <div class="flex-detail mid">
        {% translate_snippet "departmentGruppenname" lang %}
      </div>
      <div class="flex-detail mid">
        Email
      </div>
      <div class="flex-detail icon-size">
      </div>
      <div class="flex-detail icon-size">
      </div>
      <div class="flex-detail icon-size">
      </div>
      </div>
    </div>
    {% for s in htmlSlotList %}
    {{ s|safe }}
    {% endfor %}
  </div>
</div>
{% endblock content %}

project/appointment/templates/bookSlotLine.html
{% load static i18n serveContent %}
{% get_current_language as lang %}
<div class="flex-list line">
    <div class="flex-detail riesig">
      {{ date.start|date:"l" }}, {{ date.start.date }}
    </div>
    <div class="flex-detail lng">
      {{ date.start.time }} - {{ date.end.time }}
    </div>
    {% if user.is_authenticated %}
        <div class="flex-detail mid">
            <a href="/appointment/reservation?slot={{date.id}}">
              {% translate_snippet "slot_reservieren" lang %}
            </a>
        </div>
    {% endif %}
</div>

project/appointment/templates/calendar.html
{% extends "base.html" %} {% load static %}
{% load static i18n serveContent %}
{% block content %}
{% get_current_language as lang %}
<div class="container calendar"> 
  {% autoescape off %}
  {% md_to_html lang "calendar.md" as html %}
  {% unharm_html html %}
  {% endautoescape %}
{% for cal in cals %}
{{ cal|safe }}
{% endfor %}
</div>
{% endblock content %}

project/appointment/templates/dayDialog.html
<dialog class="day-overview">
    <div class="flex-list container">
        {% for date in dates %}
        <div class="flex-list line">
            <div class="flex-detail">
            {{ date.start }}
            </div>
            <div class="flex-detail">
            {{ date.end }}
            </div>
            {% if user.is_authenticated %}
                {% if date.res %}
                    <div class="flex-detail">
                    {{ date.res.department }},
                    </div>
                    <div class="flex-detail">
                    {{ date.res.user.email }}
                    </div>
                {% else %}
                    <div class="flex-detail">
                        <a href="/appointment/reservation?slot={{date.id}}">
                            Slot reservieren
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        {% endfor %}
        <form method="dialog">
            <button>OK</button>
        </form>
    </div>
</dialog>

project/appointment/templates/freeSlots.html
{% extends "base.html" %}
{% block content %}
{% load static i18n serveContent %}
{% get_current_language as lang %}
<div class="overview"> 
	{% if not user.is_authenticated %}
  {% autoescape off %}
  {% md_to_html lang "notAuthMessage.md" as html %}
  {% unharm_html html %}
  {% endautoescape %}
	{% endif %}
    <div class="flex-list container">
      <div class="flex-list line header">
        <div class="flex-detail riesig">
          {% translate_snippet "Datum" lang %}
        </div>
        <div class="flex-detail lng">
          {% translate_snippet "Zeit" lang %}
        </div>
        {% if user.is_authenticated %}
          <div class="flex-detail mid"> </div>
        {% endif %}
      </div>
      {% for s in htmlSlotList %}
      {{ s|safe }}
      {% endfor %}
    </div>
</div>
{% endblock content %}

project/appointment/templates/meinres.html
{% extends "base.html" %}
{% load static i18n serveContent %}
{% block content %}
{% get_current_language as lang %}
<div class="meine-reservierung"> 
  {% if not resTable %}
    {% autoescape off %}
    {% md_to_html lang "keine-reservierung.md" as html %}
    {% unharm_html html %}
    {% endautoescape %}
  {% else %}
    <div class="unconfirmed">
      {% autoescape off %}
      {% md_to_html lang "meine-reservierung.md" as html %}
      {% unharm_html html %}
      {% endautoescape %}
    </div>
    <div class="flex-list container">
      <div class="flex-list line header">
        <div class="flex-detail mid">
          {% translate_snippet "Datum" lang %}
        </div>
        <div class="flex-detail lng">
          {% translate_snippet "Zeit" lang %}
        </div>
        <div class="flex-detail mid">
          {% translate_snippet "departmentGruppenname" lang %}
        </div>
        <div class="flex-detail lng">
          {% translate_snippet "email" lang %}
        </div>
        <div class="flex-detail mid">
          {% translate_snippet "Bemerkung" lang %}
        </div>
        <div class="flex-detail sht">
          {% translate_snippet "Aktion" lang %}
        </div>
      </div>
      {% for t in resTable %}
      {{ t|safe }}
      {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock content %}

project/appointment/templates/meinresLine.html
{% load static i18n serveContent %}
{% get_current_language as lang %}
<div class="flex-list line data {% if not res.confirmed %}unconfirmed{% endif %}">
    <div class="flex-detail mid date">
      {{ res.slot.start.date }}
    </div>
    <div class="flex-detail lng time">
      {{ res.slot.start.time }} - {{ res.slot.end.time }}
    </div>
    <div class="flex-detail mid {% if not res.department %} empty field {% endif %}">
       {{ res.department }}
    </div>
    <div class="flex-detail lng {% if not res.user.email %} empty field {% endif %}"
         style="overflow-wrap: break-word">
       {{ res.user.email }}
    </div>
    <div class="flex-detail mid {% if not res.notes %} empty field {% endif %}">
      {{ res.notes }}
    </div>
    <div class="flex-detail sht">
        <a href="/appointment/meine-reservierung/{{res.id}}?delete=true">
          {% translate_snippet "Stornieren" lang %}
        </a>
    </div>
</div>

project/appointment/templates/reservation.html
{% extends "base.html" %} {% load static i18n serveContent %}
{% block content %}
{% get_current_language as lang %}
<div class="overview"> 
<form action="" method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <div class="error"> {{ error }} </div>
    {% endfor %}
    <div>
        <div>
          <label for="{{ form.slot.id_for_label }}">
            {% translate_snippet "DatumUndZeit" lang %}
          </label>
        </div>
        {{slot.start|date:"l"}}, {{slot.start.date}}: {{ slot.start.time }} -- {{ slot.end.time }}
        <input type="hidden" name="slot" value="{{slot.pk}}" >
    </div>
    <div>
        {{ form.department.errors }}
        <div>
          <label for="{{ form.department.id_for_label }}">
            {% translate_snippet "departmentGruppenname" lang %}
          </label>
        </div>
        {{ form.department }}
    </div>
    <div>
        {{ form.notes.errors }}
        <div>
          <label for="{{ form.notes.id_for_label }}">
            {% translate_snippet "Bemerkung" lang %}
          </label>
        </div>
        {{ form.notes }}
    </div>
    <button type="submit">
      {% translate_snippet "Senden" lang %}
    </button>
</form>
</div>
{% endblock content %}

project/appointment/templates/slotForm.html
{% extends "base.html" %} {% load static %}
{% block content %}
<h1>Slot eingeben</h1>

<form action="" method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <div class="error"> {{ error }} </div>
    {% endfor %}
    <div class="fieldWrapper">
        <label for="{{ form.start.id_for_label }}">Startzeit wählen:</label>
        <div>{{ form.start }}</div>
    </div>
    <div class="fieldWrapper">
        <label for="{{ form.end.id_for_label }}">Schlusszeit wählen:</label>
        <div>{{ form.end }}</div>
    </div>
    <input type="submit">
</form>
{% endblock content %}